services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    restart: on-failure
    ports:
      - "443:443"
    expose:
      - 443
    depends_on:
      - wordpress
      - static
      - hexo
      - adminer
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    restart: on-failure
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb
    restart: on-failure
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer
    restart: on-failure
    expose:
      - 9000
    networks:
      - inception
  ftp:
    container_name: ftp
    build: 
      context: ./requirements/bonus/ftp
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PASSWORD=${FTP_PASSWORD}
    image: ftp
    restart: on-failure
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    ports:
      - "20:20"
      - "21:21"
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis
    restart: on-failure
    volumes:
      - wordpress_vol:/var/www/html
    expose:
      - 6379
    networks:
      - inception
  static:
    container_name: static
    build: ./requirements/bonus/static
    image: static
    restart: on-failure
    volumes:
      - static_vol:/var/www/html
    expose:
      - 2053
    networks:
      - inception
  hexo:
    container_name: hexo
    build: ./requirements/bonus/hexo
    image: hexo
    restart: on-failure
    volumes:
      - hexo_vol:/blog
    expose:
      - 4000
    networks:
      - inception
volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  static_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/static
  hexo_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/hexo
networks:
  inception:
    driver: bridge

