FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y && \
    apt install -y git-core nodejs npm

RUN npm install -g hexo-cli

RUN mkdir blog
RUN hexo init blog
WORKDIR /blog
COPY ./conf/_config.yml /blog/_config.yml
RUN rm /blog/source/_posts/hello-world.md
COPY ./posts/42.md /blog/source/_posts/42.md
RUN npm install

CMD [ "hexo", "server" ]