FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y && \
    apt install -y vsftpd openssl


RUN mkdir -p /var/run/vsftpd/empty \
    && mkdir -p /etc/service/vsftpd && \
    mkdir -p /var/www/html && \
    chown -R www-data:www-data /var/www/html

RUN mkdir -p /etc/vsftpd/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/vsftpd/ssl/vsftpd.key \
    -out /etc/vsftpd/ssl/vsftpd.crt \
    -subj "/CN=localhost"

COPY ./conf/vsftpd.conf /etc/vsftpd.conf
COPY ./conf/vsftpd.chroot_list /etc/vsftpd.chroot_list

CMD ["/usr/sbin/vsftpd", "/etc/vsftpd.conf"]