FROM debian:bullseye

ARG FTP_USER
ARG FTP_PASSWORD

RUN apt-get update && apt-get upgrade -y && \
    apt install -y vsftpd openssl

RUN mkdir -p /var/run/vsftpd/empty /etc/vsftpd/ssl /var/www/html && \
    chmod 755 /var/run/vsftpd/empty && \
    chmod 755 /var/www/html

RUN mkdir -p /etc/vsftpd/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/vsftpd/ssl/vsftpd.key \
    -out /etc/vsftpd/ssl/vsftpd.crt \
    -subj "/CN=localhost"

RUN useradd -d /var/www/html $FTP_USER && echo "$FTP_USER:$FTP_PASSWORD" | chpasswd
    
COPY ./conf/vsftpd.conf /etc/vsftpd/vsftpd.conf

EXPOSE 20 21

CMD [ "vsftpd", "/etc/vsftpd/vsftpd.conf" ]