FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y && apt install -y \
    wget \
    php7.4-fpm \
    php7.4-mysqli

COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/.
RUN mkdir -p /run/php && chown -R www-data:www-data /run/php
RUN mkdir -p /var/www/html/ && chown -R www-data:www-data /var/www/html/
RUN wget -O /var/www/html/index.php https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php
CMD [ "php-fpm7.4", "-F"]
