FROM debian:bullseye

RUN apt-get update && \
    apt-get -y upgrade && \
    apt install -y \
    php7.4-redis \
    redis-server

COPY ./conf/redis.conf /etc/redis/redis.conf

# RUN echo "extension=redis.so" > /etc/php/7.4/cli/conf.d/20-redis.ini

CMD [ "redis-server" ]
