FROM debian:bullseye

RUN apt-get update && \
    apt-get -y upgrade && \
    apt install -y \
    php7.4-redis \
    redis-server

COPY ./conf/redis.conf /etc/redis/redis.conf

ENTRYPOINT [ "redis-server" ]
